require:
  - rubocop-performance

AllCops:
  NewCops: enable

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Metrics/BlockLength:
  Max: 30
  Exclude:
    - 'spec/*/*_spec.rb'

Gemspec/RequiredRubyVersion:
  Enabled: false
