require:
  - rubocop-performance

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/*/*_spec.rb'

Style/IfUnlessModifier:
  Enabled: false

Metrics/BlockLength:
  Max: 35
  Exclude:
    - 'spec/*/*_spec.rb'
