name: CI

on: [push, pull_request]

jobs:
  ruby_rails_test_matrix:
    runs-on: ubuntu-18.04

    strategy:
      matrix:
        ruby: [2.4, 2.7]

    steps:
    - uses: actions/checkout@master

    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}

    - name: Runs code QA and tests
      run: bundle && rake
